---
title: "Stats 2 Project 2"
author: "Allen Hoskins"
date: "3/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Package Setup}
library(tidyverse)
library(naniar)
library(magrittr)
library(readr)
library(glmnet)
library(caret)
library(plotmo)
library(boot)
library(MASS)
```

```{r Read in Data Set}
df = read.csv(file.choose(),header = TRUE)
df
#df = df %>% filter(df$balance != 0)
df$y <- as.factor(df$y)
df$job = factor(df$job)
df$marital = factor(df$marital)
df$education = factor(df$education)
df$default = factor(df$default)
df$housing = factor(df$housing)
df$loan = factor(df$loan)
df$contact = factor(df$contact)
df$poutcome = factor(df$poutcome)
df$month = factor(df$month)

#df$y = ifelse(df$y =="yes",1,0)
```

```{r Train/Test Split}

## 75% of the sample size
smp_size <- floor(0.80 * nrow(df))

## set the seed to make your partition reproducible
set.seed(57)
train_ind <- sample(seq_len(nrow(df)), size = smp_size)

train_df <- df[train_ind, ]
test_df <- df[-train_ind, ]



```


```{r breaking response and explinatory}
#defining response variable
train_resp = train_df$y
test_resp = test_df$y

#recode yes/no to 1 and 0
#train_resp = ifelse(train_resp =="yes",1,0)
#test_resp = ifelse(test_resp =="yes",1,0)

#defining explanatory variables
train_expl = data.matrix(train_df[,1:16])
test_expl = data.matrix(test_df[,1:16])

```

```{r find proportions of y}

prop.table(table(df$y))
```

```{r LASSO}

#cv model
lasso_cv_model = cv.glmnet(train_expl,train_resp,alpha = 1,family = 'binomial')
lasso_best_lambda = lasso_cv_model$lambda.min
best_lambda

#plot cv model
plot(lasso_cv_model)



#lasso model
lasso_best_model = glmnet(train_expl,train_resp,alpha = 1, lambda = lasso_best_lambda,family = 'binomial')
coef(lasso_best_model,lasso_best_lambda)


```


```{r ASSESS LASSO MODEL}
#assess lasso model
assess.glmnet(lasso_best_model,test_expl,test_resp, family = 'binomial',s = lasso_best_lambda)
#return confusion matrix from lasso model
confusion.glmnet(lasso_best_model,test_expl,test_resp,family = 'binomial',s=lasso_best_lambda)
#plot roc curve from lasso model
plot(roc.glmnet(lasso_best_model,test_expl,test_resp,family = 'binomial',s=lasso_best_lambda))

```


```{r RIDGE}

#cv model
ridge_cv_model = cv.glmnet(train_expl,train_resp, alpha = 0, family = 'binomial')
ridge_best_lambda = ridge_cv_model$lambda.min
ridge_best_lambda

#plot cv model
plot(ridge_cv_model)



#lasso model
ridge_best_model = glmnet(train_expl,train_resp, alpha = 0, lambda = ridge_best_lambda,family = 'binomial')
coef(ridge_best_model,ridge_best_lambda)

```

```{r ASSESS RIDGE MODEL}
#assess lasso model
assess.glmnet(ridge_best_model,test_expl,test_resp, family = 'binomial',s = ridge_best_lambda)
#return confusion matrix from lasso model
confusion.glmnet(ridge_best_model,test_expl,test_resp,family = 'binomial',s=ridge_best_lambda)
#plot roc curve from lasso model
plot(roc.glmnet(ridge_best_model,test_expl,test_resp,family = 'binomial',s=ridge_best_lambda))

```
```{r MIDDLE}

#cv model
mid_cv_model = cv.glmnet(train_expl,train_resp,alpha = 0.5,family = 'binomial')
mid_best_lambda = mid_cv_model$lambda.min
mid_best_lambda

#plot cv model
plot(mid_cv_model)



#lasso model
mid_best_model = glmnet(train_expl,train_resp,alpha = 0.5, lambda = mid_best_lambda,family = 'binomial')
coef(mid_best_model,mid_best_lambda)


```


```{r ASSESS MIDDLE MODEL}
#assess lasso model
assess.glmnet(mid_best_model,test_expl,test_resp, family = 'binomial',s = mid_best_lambda)
#return confusion matrix from lasso model
confusion.glmnet(mid_best_model,test_expl,test_resp,family = 'binomial',s=mid_best_lambda)
#plot roc curve from lasso model
plot(roc.glmnet(mid_best_model,test_expl,test_resp,family = 'binomial',s=mid_best_lambda))

```


```{r relaxed lasso}

#cv model
relaxed_cv_model = cv.glmnet(train_expl,train_resp,alpha = 1,family = 'binomial',relax = TRUE)
relaxed_best_lambda = relaxed_cv_model$lambda.min

#plot cv model
plot(relaxed_cv_model)



#lasso model
relaxed_best_model = glmnet(train_expl,train_resp,alpha = 1, lambda = relaxed_best_lambda,family = 'binomial',relax = TRUE)
coef(relaxed_best_model,relaxed_best_lambda)

relaxed_best_model

coefs = coef(relaxed_best_model)[,1]
coefs = sort(abs(coefs), decreasing = F)
coefs
relax_var_imp = varImp(relaxed_best_model,lambda = relaxed_best_lambda, scale = FALSE)
relax_var_imp
```


```{r ASSESS MIDDLE MODEL}
#assess lasso model
assess.glmnet(relaxed_best_model,test_expl,test_resp, family = 'binomial',s = mid_best_lambda,relax = TRUE)
#return confusion matrix from lasso model
confusion.glmnet(relaxed_best_model,test_expl,test_resp,family = 'binomial',s=mid_best_lambda,relax = TRUE)
#plot roc curve from lasso model
plot(roc.glmnet(relaxed_best_model,test_expl,test_resp,family = 'binomial',s=mid_best_lambda,relax = TRUE))

```

```