```{r Package Setup}
library(tidyverse)
library(ggplot2)
```
# # # # # # 
```{r dataset}
#reading in the data
df <- read.csv(file.choose(), header = T, fileEncoding="UTF-8-BOM")
df
```
# # # # # # 
```{r EDA}
#visualization dependencies
library(GGally)
library(forcats)
library(dplyr)

#changing the duration column from seconds to minutes
df$duration<−df$duration/60
df

#a view of the yes and no counts for the response variable
valuecounts = df$y
table(valuecounts)

#looking for correlations between continous variables
ggpairs(df,columns=c(1,6,12,14,15,17),aes(colour=y))

#bar chart of Yes/No proportions for response
p = ggplot(df,aes(x = fct_infreq(job), fill=y)) + 
	geom_bar(stat = 'count') +
  theme(axis.text.x=element_text(angle=90)) +
  ggtitle("Proportions of Yes/No by Job Sector") +
  xlab("Job Sector") +
  ylab("Count")
p + theme(axis.text.x=element_text(vjust=0.5)) #Adjusting tick label positions
p <- p + guides(fill=guide_legend(title="Response")) #Changing the legend title

#Scatter plot of Yes/No for Age vs. Duration
ggplot(df, aes(x=age, y=duration, color=y)) +
  geom_point() +
  #geom_jitter() +
  ggtitle("Relationship of Age vs. Call Duration - Group By Client Response") +
  ylab("Duration (minutes)") +
  xlab("Age") + 
  labs(color='Response')

#Summary statistics of continuous variables
t(aggregate(balance~y,data=df,summary))
t(aggregate(age~y,data=df,summary))
t(aggregate(previous~y,data=df,summary))
t(aggregate(duration~y,data=df,summary))
t(aggregate(campaign~y,data=df,summary))
t(aggregate(pdays~y,data=df,summary))
```
# # # # # #
```{r Additional EDA}

#histogram of age
age_vizz = ggplot(df, aes(x = age))
age_vizz + geom_density(fill = "#377eb8", alpha=0.6) +
  geom_vline(aes(xintercept = mean(age)), 
             linetype = "dashed", size = 0.6,
             color = "#FC4E07") +
  ylab("Frequency") +
  ggtitle("Distribution of Age") +
  xlab("Age")

#bar chart of Yes/No proportions by whether or not they have a personal loan already
p2 = ggplot(df,aes(x = fct_infreq(loan), fill=y)) + 
	geom_bar(stat = 'count') +
  theme(axis.text.x=element_text(angle=90)) +
  ggtitle("Proportions of Yes/No by Loan") +
  xlab("Loan") +
  ylab("Count")
p2 + theme(axis.text.x=element_text(vjust=0.5)) #Adjusting tick label positions
pnew <- p2 + guides(fill=guide_legend(title="Response")) #Changing the legend title
pnew

#PCA
df.pr <- prcomp(df[c(1,6,10,12,13,14,15)], center = TRUE, scale = TRUE)
summary(df.pr)

screeplot(df.pr, type = "l", npcs = 15, main = "Screeplot of the 7 PCs")
abline(h = 1, col="red", lty=5)
legend("topright", legend=c("Eigenvalue = 1"),
       col=c("red"), lty=5, cex=0.6)

cumpro <- cumsum(df.pr$sdev^2 / sum(df.pr$sdev^2))
plot(cumpro[0:15], xlab = "PC #", ylab = "Amount of explained variance", main = "Cumulative variance plot")
abline(v = 6, col="blue", lty=5)
abline(h = 0.88759, col="blue", lty=5)
legend("topleft", legend=c("Cut-off @ PC6"),
       col=c("blue"), lty=5, cex=0.6)

plot(df.pr$x[,1],df.pr$x[,2], xlab="PC1", ylab = "PC2", main = "PC1 / PC2 - plot")

library("factoextra")
fviz_pca_ind(df.pr, geom.ind = "point", pointshape = 21, 
             pointsize = 2, 
             fill.ind = df$y, 
             col.ind = "black", 
             palette = "jco", 
             addEllipses = TRUE,
             label = "var",
             col.var = "black",
             repel = TRUE,
             legend.title = "Response") +
  ggtitle("2D PCA-plot from 7 feature dataset") +
  theme(plot.title = element_text(hjust = 0.5))
```
